import React from 'react'
import documentBuilder from '../util/documentBuilder'
import reactBuilder from '../util/reactBuilder'
import About from '../app/About'
import Index from '../app/Index'
import Err404 from '../app/Err404'
const fs = require('fs');

//Define here the routes of your app
export default (app) =>{

  //Clean react public folder
  try{
    const files = fs.readdirSync("./public/react/");
    files.forEach((file)=>{
      if(file != ".getkeep"){
        fs.unlinkSync('./public/react/' + file);
      }
    })
  }catch(err){
    console.log("Error cleaning React client files")
  }

  app.get('/', function(req, res){
    //Builds the basic html structure, render the component in server side and sends the compiled component to client
    const html = new documentBuilder(<Index/>, this.hash_filename);
    //Sets header in document
    html.setHeader(<meta key={1} charSet="UTF-8"/>)
    html.setHeader(<title key={2} >ReactLS - Index</title>)
    html.setHeader(<link key={3} rel="shortcut icon" href="/public/resources/images/favicon.ico" type="image/x-icon"/>)
    html.setHeader(<link key={4} rel="icon" href="/public/resources/images/favicon.ico" type="image/x-icon"/>)
    //Sending the response with built html
    res.send(html.buildDocument())
  }
  //Binds the hash_filename variable to name of the compilated js file generated by webpack in public 
  .bind({hash_filename: reactBuilder("./src/app/Index.js")}));

  app.get(['/about','/about/1', '/about/2'], function(req, res){
    //inform the request url and the component will render correctly in server side
    const html = new documentBuilder(<About location={req.url} />, this.hash_filename);
    //Can also set all headers in one command
    html.setHead(
      <head>
        <meta charSet="utf-8"/>
        <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0"/>
        <meta key={1} charSet="UTF-8"/>
        <title>ReactLS - About</title>
        <link rel="shortcut icon" href="/public/resources/images/favicon.ico" type="image/x-icon"/>
        <link rel="icon" href="/public/resources/images/favicon.ico" type="image/x-icon"/>
      </head>
    )
    res.send(html.buildDocument())
  }.bind({hash_filename: reactBuilder("./src/app/About.js")}))

  app.get('*', function(req, res){
    const html = new documentBuilder(<Err404/>, this.hash_filename);
    html.setHead(
      <head>
        <meta charSet="utf-8"/>
        <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0"/>
        <meta key={1} charSet="UTF-8"/>
        <title>ReactLS - Not Found</title>
        <link rel="shortcut icon" href="/public/resources/images/favicon.ico" type="image/x-icon"/>
        <link rel="icon" href="/public/resources/images/favicon.ico" type="image/x-icon"/>
      </head>
    )
    res.status(404).send(html.buildDocument())
  }.bind({hash_filename: reactBuilder("./src/app/Err404.js")}));

}
